name: ci

on:
  push:
    branches:
      - 'main'

env:
  NGINX_VERSION: 1.23

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            NGINX_VERSION=${{ env.NGINX_VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/nginx-fancyindex:${{ env.NGINX_VERSION }}
            ghcr.io/${{ github.actor }}/nginx-fancyindex:latest
